### ISSUE TITLE
[增强组件] 表单设计器

### ISSUE THREAD

**Issue by zhou-hao** [hs-web/hsweb-ui-layui#2]
- [x] 常用控件增删
 - [x] 拖拽修改控件位置
 - [x] 修改属性,实时更新表单信息

**Comment by Licoy** [comment]
实时更新表单属性，建议可以使用layui+vue配合实现

**Comment by zhou-hao** [comment]
@Licoy 然而还是使用了原生js方式。

**Comment by zhou-hao** [comment]
https://github.com/hs-web/hsweb-ui-layui/tree/master/modules/form
